### PR TITLE
Allow including Serializable to write custom adapters

### PR DESCRIPTION
**Pull request by elbywan**
### Purpose

Make `OpenAPI::Generator::Serializable` an includable module to make writing adapters easier.

See #17 for a detailed explanation.

ping @dukeraphaelng 

### Usage

`OpenAPI::Generator::Serializable` can now be `included` as well as `extended`.

- `extend`: same as before, a class that extends Serializable will be using the regular logic to generate its schema (parsing instance vars).
- `include`: adapters can override `generate_schema` while still providing the same registration capabilities when extended.

```crystal
module Adapter
  # Inherits schema generation methods from `Serializable`.
  # Classes extending this adapter will also register themselves as being serializable.
  include OpenAPI::Generator::Serializable

  # Custom schema generation logic.
  def generate_schema
    # add logic here…
  end
end

module Model
  # `Adapter` can be extended just like `OpenAPI::Generator::Serializable`.
  extend Adapter
end
```

Complete self-contained example:

```crystal
require "openapi-generator"
require "file_utils"

module SerializerAdapter
  include OpenAPI::Generator::Serializable

  def generate_schema
    OpenAPI::Schema.new(
      type: "object",
      properties: {
        "one" => OpenAPI::Schema.new(type:"string")
      },
      required: ["one"]
    )
  end
end

# Uses the SerializerAdapter logic.
module AdapterModel
  extend SerializerAdapter
end

# Uses the default logic.
module RegularModel
  extend OpenAPI::Generator::Serializable

  property two : Int32 = 0
end

p! AdapterModel.generate_schema.to_yaml
# => "---\nrequired:\n- one\ntype: object\nproperties:\n  one:\n    type: string\n"
p! AdapterModel.to_openapi_schema.to_yaml
# => "---\nallOf:\n- $ref: '#/components/schemas/AdapterModel'\n"
p! {{  OpenAPI::Generator::Serializable::SERIALIZABLE_CLASSES.id.stringify }}
# => "[AdapterModel, RegularModel] of Class"

class MockProvider < OpenAPI::Generator::RoutesProvider::Base
  def route_mappings : Array(OpenAPI::Generator::RouteMapping)
    [] of OpenAPI::Generator::RouteMapping
  end
end

OpenAPI::Generator.generate(
  MockProvider.new,
  options:  {
    output: Path[Dir.current] / "openapi_test.yaml",
  },
  base_document: {
    info:       {title: "Test", version: "0.0.1"},
    components: NamedTuple.new,
  }
)

puts File.read("openapi_test.yaml")

# ---
# openapi: 3.0.1
# info:
#   title: Test
#   version: 0.0.1
# paths: {}
# components:
#   schemas:
#     AdapterModel:
#       required:
#       - one
#       type: object
#       properties:
#         one:
#           type: string
#     RegularModel:
#       required:
#       - two
#       type: object
#       properties:
#         two:
#           type: integer
#   responses: {}
#   parameters: {}
#   examples: {}
#   requestBodies: {}
#   headers: {}
#   securitySchemes: {}
#   links: {}
#   callbacks: {}

FileUtils.rm("openapi_test.yaml")
```

### CODE REVIEW

**Comment by dukenguyenxyz** [comment]
I reckon since we are changing the API from `OpenAPI::Generator::Serializable#generate_schema` to `OpenAPI::Generator::Serializable::Utils#generate_schema`, this should be a major release. so `version: 1.0.4` -> `version: 2.0.0`

**Comment by dukenguyenxyz** [comment]
It'd also be a good idea to add your self-contained example to the specs

**Comment by elbywan** [comment]
> I reckon since we are changing the API from OpenAPI::Generator::Serializable#generate_schema to OpenAPI::Generator::Serializable::Utils#generate_schema

> version: 1.0.4 -> version: 2.0.0

~It should not be necessary to major bump, the `macro generate_schema` is internal and not part of the "public" api surface.~

EDIT: on second thought, adapters use the macro and you're right a major version bump is needed.

> It'd also be a good idea to add your self-contained example to the specs

👍

**Review by dukenguyenxyz — APPROVED** [review]
LGTM!

**Pull request merged**
